# Prod and qa both are having same content 
# as images are fetched from same repository 
# Ensure namespace value and text appended to name are same and this namespace exists in k8s
apiVersion: v1
kind: Secret
metadata:
  name: cloud-gateway-docker-config-production
  namespace: production
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJhM1ZpWlMxamJHOTFaQzFuWVhSbGQyRjVMWEIxYkd4bGNqcE1OMUJtVUV0dmVubzVla2RCTVdsdGJYbzNjdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson