apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raptor-nfs-pvc-production
  namespace: production
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 5Gi