apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service-app
  labels:
    app: job-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-service-app
  template:
    metadata:
      labels:
        app: job-service-app
    spec:
      imagePullSecrets:
        - name: job-service-docker-config-_NAMESPACE_
      volumes:
      - name: raptor-volume
        persistentVolumeClaim:
          claimName: raptor-nfs-pvc-_NAMESPACE_
      containers:
        - name: job-service-app
          image: _IMAGE_NAME_
          volumeMounts:
          - name: raptor-volume
            mountPath: /mnt/raptordata
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: raptor-configmap-_NAMESPACE_
                  key: spring_app_json
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: raptor-configmap-_NAMESPACE_
                  key: spring_profile     
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: raptor-configmap-_NAMESPACE_
                  key: datasource_host
            - name: SPRING_DATASOURCE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: raptor-secrets-_NAMESPACE_
                  key: job_service_db_name
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: raptor-secrets-_NAMESPACE_
                  key: job_service_db_username
            - name: SPRING_DATASOURCE_PWD
              valueFrom:
                secretKeyRef:
                  name: raptor-secrets-_NAMESPACE_
                  key: job_service_db_pwd
