apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app : user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      volumes:
      - name: raptor-volume
        persistentVolumeClaim:
          claimName: raptor-nfs-pvc-_NAMESPACE_
      imagePullSecrets:
      - name: user-service-docker-config-_NAMESPACE_
      containers:
      - name: user-service-app
        image: _IMAGE_NAME_
        imagePullPolicy: Always
        ports:
          - containerPort: 9093
        volumeMounts:
        - name: raptor-volume
          mountPath: /mnt/raptordata
        env:
          - name: SPRING_APPLICATION_JSON
            valueFrom:
              configMapKeyRef:
                name: raptor-configmap-_NAMESPACE_
                key: spring_app_json
          - name: SPRING_DATASOURCE_HOST
            valueFrom:
              configMapKeyRef:
                name: raptor-configmap-_NAMESPACE_
                key: datasource_host
          - name: SPRING_DATASOURCE_DB_NAME
            valueFrom:
              secretKeyRef:
                name: raptor-secrets-_NAMESPACE_
                key: user_service_db_name
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: raptor-secrets-_NAMESPACE_
                key: user_service_db_username
          - name: SPRING_DATASOURCE_PWD
            valueFrom:
              secretKeyRef:
                name: raptor-secrets-_NAMESPACE_
                key: user_service_db_pwd