apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raptor-nfs-pvc-qa
  namespace: qa
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 5Gi